index:
    path: /
    controller: App\Controller\DefaultController::index
    
contacto:
    path: /contacto
    controller: App\Controller\ContactoController::showForm

create_contacto:
    path: /crearcontacto
    controller: App\Controller\ContactoController::createProduct