index:
    path: /
    controller: App\Controller\DefaultController::index
    
new_contacto:
    path: /new-contacto
    controller: App\Controller\ContactoController::new

seeding_yesterday:
    path: /seeding-yesterday
    controller: App\Controller\DefaultController::seedingYesterday

